local deftest = require("deftest.deftest")

local tests = {
	require("test.adam.test_basic_adam"),
	require("test.adam.test_actions_behaviour"),
	require("test.adam.test_actions_time_behaviour"),
	require("test.actions.test_math"),
}


function init(self)
	print('[DefTest]: Init of DefTest')
	for i = 1, #tests do
		deftest.add(tests[i])
	end

	local is_report = (sys.get_config("test.report") == "1")
	deftest.run({ coverage = { enabled = is_report } })
end
